### ISSUE TITLE
[feat] 기초 세팅

### ISSUE THREAD

**Issue by hanseulhee** [primus-teoSprint/primus_FE#1]
### ❤️‍🔥 어떤 개발 사항인가요?

기초 세팅을 진행합니다

### ✍🏻 TODO

- [x]  필요한 패키지 설치
- [x]  디렉토리 구조 설정
- [x]  eslint, prettier
- [x] husky
- [x] ci
- [x] style 설정
- [x] layout 설정
- [x] react-query provider
